### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jacobsax**
Added Senario builder class, created empty functions for said class #

### CODE REVIEW

**Comment by Comprs** [comment]
Lots of junk merges in this one. May what to fix that before merging this in.

**Comment by jacobsax** [comment]
How do I get rid of them?

**Comment by jacobsax** [comment]
Can't remove them, they're valid merges

**Comment by Comprs** [comment]
A rebase is needed

**Comment by jacobsax** [comment]
But they will appear again every time I update my branch with the main?

**Comment by jacobsax** [comment]
Just rebased through terminal, no different

**Comment by Comprs** [comment]
The problem here is that you really should be committing any work you do to new short lived branches and keep develop and master to reflect the state of the master repository.

**Comment by Comprs** [comment]
You should be able to rebase using
```
git rebase -i upstream/develop;
git push -f origin develop;
```

**Pull request closed without merging**
